<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c5126c69-0b1e-4211-9a3c-7a7bd30ec8aa</elementGuidId>
    <imagePath></imagePath>
    <name>link_AdvertiseYourProducts</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/div[1]/div[3]/ul[1]/li[5]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="navFooterLinkCol\ navAccessibility"]:nth-child(3) li:nth-child(5) &gt; [class="nav_a"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'https://advertising.amazon.com/?ref=ext_amzn_ftr') and equals(@text,'Advertise Your Products')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Advertise Your Products"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>https://advertising.amazon.com/?ref=ext_amzn_ftr</value>
        <webElementGuid>768dde0b-f330-46cc-97e7-91edc8514cc9</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Advertise Your Products</value>
        <webElementGuid>768dde0b-f330-46cc-97e7-91edc8514cc9</webElementGuid>
    </webElementProperties>
</WebElementEntity>