<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5d382d34-0349-4127-9ad1-7f8332d8e4d2</elementGuidId>
    <imagePath></imagePath>
    <name>link_Mattresses</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[3]/div[1]/div[1]/div[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="bxc-grid__column\ \ bxc-grid__column--2-of-12\ \ \ bxc-grid__column--light"]:nth-child(3) [class="bxc-grid-overlay__link"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/b/ref=s9_bw_cg_vasFurLP_3c1_w?node=122326751011&amp;ref_=vasFurLP_bubbler03&amp;pf_rd_m=ATVPDKIKX0DER&amp;pf_rd_s=merchandised-search-1&amp;pf_rd_r=977VDV0KMPBW8034A5A2&amp;pf_rd_t=101&amp;pf_rd_p=9ec9e301-d3b8-447b-9360-354fdc940233&amp;pf_rd_i=122326748011') and equals(@text,'')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="Mattresses and&lt;br&gt;mattress"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/b/ref=s9_bw_cg_vasFurLP_3c1_w?node=122326751011&amp;ref_=vasFurLP_bubbler03&amp;pf_rd_m=ATVPDKIKX0DER&amp;pf_rd_s=merchandised-search-1&amp;pf_rd_r=977VDV0KMPBW8034A5A2&amp;pf_rd_t=101&amp;pf_rd_p=9ec9e301-d3b8-447b-9360-354fdc940233&amp;pf_rd_i=122326748011</value>
        <webElementGuid>768dde0b-f330-46cc-97e7-91edc8514cc9</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value></value>
        <webElementGuid>768dde0b-f330-46cc-97e7-91edc8514cc9</webElementGuid>
    </webElementProperties>
</WebElementEntity>