<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>dffd59f8-af9b-4214-8ef7-927d923d63f0</elementGuidId>
    <imagePath></imagePath>
    <name>link_CasperSleepElement</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[3]/div[1]/div[1]/div[1]/div[4]/div[2]/span[1]/div[1]/div[1]/div[2]/div[1]/h2[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="_octopus-search-result-card_style_apbSearchResultItem__2-mx4"]:nth-child(2) [class="a-link-normal\ s-underline-text\ s-underline-link-text\ s-link-style\ a-text-normal"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/Casper-Sleep-Element-Mattress-Queen/dp/B085H466BX/ref=lp_122326751011_1_2?pf_rd_p=53d84f87-8073-4df1-9740-1bf3fa798149&amp;pf_rd_r=RVMB21T5R3GHKAYKDMQH&amp;sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D') and equals(@text,'Casper Sleep Element, Queen Medium Firm Mattress - Memory Foam + Support - 100-Night Trial - CertiPUR-US Mattress, Grey')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Casper Sleep Element, Queen"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/Casper-Sleep-Element-Mattress-Queen/dp/B085H466BX/ref=lp_122326751011_1_2?pf_rd_p=53d84f87-8073-4df1-9740-1bf3fa798149&amp;pf_rd_r=RVMB21T5R3GHKAYKDMQH&amp;sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D</value>
        <webElementGuid>768dde0b-f330-46cc-97e7-91edc8514cc9</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Casper Sleep Element, Queen Medium Firm Mattress - Memory Foam + Support - 100-Night Trial - CertiPUR-US Mattress, Grey</value>
        <webElementGuid>768dde0b-f330-46cc-97e7-91edc8514cc9</webElementGuid>
    </webElementProperties>
</WebElementEntity>