<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ebff5199-7109-4c13-9d00-747b216e6623</elementGuidId>
    <imagePath></imagePath>
    <name>header_EarthsBiggestSelection</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/div[4]/div[1]/div[1]/div[2]/div[1]/div[1]/h3[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="a-section\ a-spacing-none\ _gift-registry-icon-highlights-desktop_style_iconHighlightBody__Yl8Gm"]:nth-child(1) [class="a-size-medium\ a-spacing-mini\ _gift-registry-icon-highlights-desktop_style_iconHighlightHeader__XrnXm"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=heading[name="Earth's biggest selection"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>