<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7a49f26c-a7f9-4499-934e-b08a17732342</elementGuidId>
    <imagePath></imagePath>
    <name>header_KeepTrackOfEverything</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/div[6]/div[1]/div[2]/div[2]/div[1]/h3[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="a-section\ a-spacing-none\ _gift-registry-image-highlights-desktop_style_imageHighlightBody__8Z-nI"]:nth-child(2) [class="a-size-medium\ a-spacing-mini\ _gift-registry-image-highlights-desktop_style_imageHighlightsHeader__ue5r1"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=heading[name="Keep track of everything"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>