<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5f606fb8-4df5-459b-b804-6728571059da</elementGuidId>
    <imagePath></imagePath>
    <name>link_DogsOfAmazon</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>a:nth-child(2)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/dogsofamazon') and equals(@text,'')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Dogs of Amazon"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/dogsofamazon</value>
        <webElementGuid>768dde0b-f330-46cc-97e7-91edc8514cc9</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value></value>
        <webElementGuid>768dde0b-f330-46cc-97e7-91edc8514cc9</webElementGuid>
    </webElementProperties>
</WebElementEntity>