<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e758cd3d-369b-4100-9ab1-7bfa9949192c</elementGuidId>
    <imagePath></imagePath>
    <name>link_CustomerService</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/header[1]/div[1]/div[4]/div[2]/div[2]/div[1]/a[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="nav-a\ \ "]:nth-child(3)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/gp/help/customer/display.html?nodeId=508510&amp;ref_=nav_cs_customerservice') and equals(@text,'Customer Service')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Customer Service"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/gp/help/customer/display.html?nodeId=508510&amp;ref_=nav_cs_customerservice</value>
        <webElementGuid>f90871f8-3293-4476-be80-09da2df3a6bd</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Customer Service</value>
        <webElementGuid>f90871f8-3293-4476-be80-09da2df3a6bd</webElementGuid>
    </webElementProperties>
</WebElementEntity>