<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e8eb935f-008b-4af3-acc0-a9f0192fae60</elementGuidId>
    <imagePath></imagePath>
    <name>button_Close</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[8]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/header[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="a-declarative\ _tell-amazon-desktop_style_tell_amazon_button_close__3JLWO"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#a-popover-content-5 &gt;&gt; internal:label="Close"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value></value>
        <webElementGuid>768dde0b-f330-46cc-97e7-91edc8514cc9</webElementGuid>
    </webElementProperties>
</WebElementEntity>