<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d9a213c4-7cbc-4b2f-b385-ad7e67b4324b</elementGuidId>
    <imagePath></imagePath>
    <name>div_ValidPhoneMessage</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[4]/div[4]/form[1]/div[8]/div[1]/div[1]/div[1]/div[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#gc-delivery-mechanism-form-MobileSMS [class="a-fixed-left-grid-col\ gc-order-form-right\ gc-field-wrapper\ gc-field-wrapper-recipients\ a-col-right"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="+1 Please enter a valid phone"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>