<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c16b9f1e-361a-409e-8696-53316c53acc3</elementGuidId>
    <imagePath></imagePath>
    <name>input_Submit</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[13]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[8]/td[4]/div[1]/span[2]/span[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="a-button\ a-button-primary\ _export-alternative-card-desktop_style_export_alternative_cta_button__22AJK\ a-button-focus"] [type="submit"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'submit')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="Submit"i] &gt;&gt; nth=2</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>submit</value>
        <webElementGuid>768dde0b-f330-46cc-97e7-91edc8514cc9</webElementGuid>
    </webElementProperties>
</WebElementEntity>