<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2be6616d-c0d8-4003-8470-dd3bc38b331f</elementGuidId>
    <imagePath></imagePath>
    <name>link_RingPeepholeCamera</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[4]/nav[1]/ul[1]/li[2]/div[3]/div[1]/div[1]/div[1]/div[2]/div[1]/ol[1]/li[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="a-size-base\ a-link-normal\ mn-product-card\ mn-link\ js-pc-B0BLXZ6HLT"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/dp/B0BLXZ6HLT?ref=MARS_NAV_desktop_db_cam_battdoorbells_rpcam') and equals(@text,'Ring Peephole Camera
            Upgrade your peephole with smart security')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Ring Peephole Camera Ring"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/dp/B0BLXZ6HLT?ref=MARS_NAV_desktop_db_cam_battdoorbells_rpcam</value>
        <webElementGuid>768dde0b-f330-46cc-97e7-91edc8514cc9</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Ring Peephole Camera
        Upgrade your peephole with smart security</value>
        <webElementGuid>768dde0b-f330-46cc-97e7-91edc8514cc9</webElementGuid>
    </webElementProperties>
</WebElementEntity>