<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7fa132d6-acbb-4d4f-81e0-e3ed4d21f47a</elementGuidId>
    <imagePath></imagePath>
    <name>link_ManageYourContentAndDevices</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[10]/div[2]/div[1]/ul[3]/li[20]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="hmenu\ hmenu-visible\ hmenu-translateX"] &gt; li:nth-child(20) &gt; [class="hmenu-item"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/gp/digital/fiona/manage?ref_=nav_em__ods_eink_con_myk_0_2_3_17') and equals(@text,'Manage Your Content and Devices')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#hmenu-content &gt;&gt; internal:role=link[name="Manage Your Content and"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/gp/digital/fiona/manage?ref_=nav_em__ods_eink_con_myk_0_2_3_17</value>
        <webElementGuid>768dde0b-f330-46cc-97e7-91edc8514cc9</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Manage Your Content and Devices</value>
        <webElementGuid>768dde0b-f330-46cc-97e7-91edc8514cc9</webElementGuid>
    </webElementProperties>
</WebElementEntity>