<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>37b723a0-2594-412f-88c6-f3c1a5285cd0</elementGuidId>
    <imagePath></imagePath>
    <name>link_KindleEreadersAndBooks2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[8]/div[2]/div[1]/ul[1]/li[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="hmenu\ hmenu-visible"] &gt; li:nth-child(3) &gt; [class="hmenu-item"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'') and equals(@text,'Kindle E-readers &amp; Books')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Kindle E-readers &amp; Books"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value></value>
        <webElementGuid>768dde0b-f330-46cc-97e7-91edc8514cc9</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Kindle E-readers &amp; Books</value>
        <webElementGuid>768dde0b-f330-46cc-97e7-91edc8514cc9</webElementGuid>
    </webElementProperties>
</WebElementEntity>