<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>dbc2ffb7-bbdc-4405-9481-e73c5338a3ed</elementGuidId>
    <imagePath></imagePath>
    <name>link_SubwayEGiftCard</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/ol[1]/li[3]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#anonCarousel1 #acsProductBlockV1-2 &gt; [class="a-color-base\ a-spacing-none\ a-link-normal"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'https://www.amazon.com/Subway-Gift-Cards-Email-Delivery/dp/B07YP72NNP/ref=s9_acsd_al_ot_c2_x_2_t?_encoding=UTF8&amp;pf_rd_m=ATVPDKIKX0DER&amp;pf_rd_s=merchandised-search-4&amp;pf_rd_r=2K5R1419GGJ85N0GY3V9&amp;pf_rd_p=5fa5254d-d423-4d5b-82ab-523488885131&amp;pf_rd_t=&amp;pf_rd_i=2864196011') and equals(@text,'Subway eGift Card
            Subway eGift Card
            SUBWAY
            SUBWAY')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Subway eGift Card Subway"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>https://www.amazon.com/Subway-Gift-Cards-Email-Delivery/dp/B07YP72NNP/ref=s9_acsd_al_ot_c2_x_2_t?_encoding=UTF8&amp;pf_rd_m=ATVPDKIKX0DER&amp;pf_rd_s=merchandised-search-4&amp;pf_rd_r=2K5R1419GGJ85N0GY3V9&amp;pf_rd_p=5fa5254d-d423-4d5b-82ab-523488885131&amp;pf_rd_t=&amp;pf_rd_i=2864196011</value>
        <webElementGuid>768dde0b-f330-46cc-97e7-91edc8514cc9</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Subway eGift Card
        Subway eGift Card
        SUBWAY
        SUBWAY</value>
        <webElementGuid>768dde0b-f330-46cc-97e7-91edc8514cc9</webElementGuid>
    </webElementProperties>
</WebElementEntity>