<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a1523c56-bfd4-4671-aeec-6396e419b073</elementGuidId>
    <imagePath></imagePath>
    <name>link_ProductCard</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[43]/div[1]/div[1]/div[1]/div[2]/div[3]/div[1]/div[1]/div[2]/div[3]/div[1]/div[1]/div[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@data-testid,'product-card-link') and equals(@href,'https://www.amazon.com/Blink-Outdoor-4th-Gen-Mini/dp/B0DGMMS8BP?ref=dlx_prime_dg_dcl_B0DGMMS8BP_dt_sl7_f2') and equals(@text,'59% off
            Prime Big Deal
            
            Blink Outdoor 4 (4th Gen) + Blink Mini – Smart security camera, two-way talk, HD live view, motion detection, set up in minutes, Works with Alexa – 8 camera system + Mini (White)
            Blink Outdoor 4 (4th Gen) + Blink Mini – Smart security ca…')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-testid="B0DGMMS8BP"] [data-testid="product-card-link"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>data-testid</name>
        <type>Main</type>
        <value>product-card-link</value>
        <webElementGuid>768dde0b-f330-46cc-97e7-91edc8514cc9</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>https://www.amazon.com/Blink-Outdoor-4th-Gen-Mini/dp/B0DGMMS8BP?ref=dlx_prime_dg_dcl_B0DGMMS8BP_dt_sl7_f2</value>
        <webElementGuid>768dde0b-f330-46cc-97e7-91edc8514cc9</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>59% off
        Prime Big Deal
        
        Blink Outdoor 4 (4th Gen) + Blink Mini – Smart security camera, two-way talk, HD live view, motion detection, set up in minutes, Works with Alexa – 8 camera system + Mini (White)
        Blink Outdoor 4 (4th Gen) + Blink Mini – Smart security ca…</value>
        <webElementGuid>768dde0b-f330-46cc-97e7-91edc8514cc9</webElementGuid>
    </webElementProperties>
</WebElementEntity>