<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9097f088-18eb-40fa-9b07-d554ec349a93</elementGuidId>
    <imagePath></imagePath>
    <name>link_LANEIGELipGlowyBalm</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[39]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/ol[1]/li[2]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#anonCarousel10 [class="a-carousel-card\ dcl-carousel-element"]:nth-child(2) [class="a-link-normal\ dcl-product-link"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/Laneige-Lip-Glowy-Balm-Berry/dp/B07DY2QRF6?pd_rd_w=vIjmq&amp;content-id=amzn1.sym.6a97845c-a7d8-4403-887b-eaf41b51ab1b&amp;pf_rd_p=6a97845c-a7d8-4403-887b-eaf41b51ab1b&amp;pf_rd_r=406FXHYPBDXAT0E6E6SH&amp;pd_rd_wg=5Z56m&amp;pd_rd_r=cff489d5-42b3-43fb-aea8-aec2b8d70328&amp;pd_rd_i=B07DY2QRF6') and equals(@text,'30% off
            Prime Big Deal
            $13.30
            $13
            30
            List Price:
            $19.00
            $19.00
            LANEIGE Lip Glowy Balm Hydrate, Glossy, Lightweight, Moisturize &amp; Tint with Shea Butter
            LANEIGE Lip Glowy Balm Hydrate,…')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="LANEIGE Lip Glowy Balm"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/Laneige-Lip-Glowy-Balm-Berry/dp/B07DY2QRF6?pd_rd_w=vIjmq&amp;content-id=amzn1.sym.6a97845c-a7d8-4403-887b-eaf41b51ab1b&amp;pf_rd_p=6a97845c-a7d8-4403-887b-eaf41b51ab1b&amp;pf_rd_r=406FXHYPBDXAT0E6E6SH&amp;pd_rd_wg=5Z56m&amp;pd_rd_r=cff489d5-42b3-43fb-aea8-aec2b8d70328&amp;pd_rd_i=B07DY2QRF6</value>
        <webElementGuid>f90871f8-3293-4476-be80-09da2df3a6bd</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>30% off
        Prime Big Deal
        $13.30
        $13
        30
        List Price:
        $19.00
        $19.00
        LANEIGE Lip Glowy Balm Hydrate, Glossy, Lightweight, Moisturize &amp; Tint with Shea Butter
        LANEIGE Lip Glowy Balm Hydrate,…</value>
        <webElementGuid>f90871f8-3293-4476-be80-09da2df3a6bd</webElementGuid>
    </webElementProperties>
</WebElementEntity>